version: '3.8'

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb-container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: parcial_db
      MARIADB_USER: root
      MARIADB_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backup:/backup
    networks:
      - parcial_net

  backup:
    image: mariadb:11.3
    container_name: mariadb-backup
    depends_on:
      - mariadb
    entrypoint: >
      /bin/sh -c "
      while true; do
        timestamp=$(date +\"%Y-%m-%d_%H-%M-%S\");
        mysqldump -hmariadb-container -uroot -prootpassword parcial_db > /backup/backup_$${timestamp}.sql;
        sleep 86400;
      done
      "
    volumes:
      - ./backup:/backup
    networks:
      - parcial_net

  microservicio:
    image: brahiancg/bcaceresa:latest
    container_name: microservicio-parcial
    restart: always
    ports:
      - "4500:4500"
    environment:
      # Variables utilizadas en application.properties (se pueden sobreescribir aquí)
      SPRING_APPLICATION_NAME: primero
      SERVER_PORT: 4500
      # Es importante que el URL de la BD use el nombre del contenedor de la DB
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb-container:3306/parcial_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    depends_on:
      - mariadb
    networks:
      - parcial_net

volumes:
  mariadb_data:

networks:
  parcial_net:
